import { Route, Routes } from 'react-router-dom'
import './App.css'
import Home from './Routes/Home'
import Header from './Components/Header/Header'
import Footer from './Components/Footer/Footer'
import Admin from './Routes/Admin'
import AddProduct from './Routes/AddProduct'
import { useState } from 'react';
import Detail from './Routes/Detail'
import Register from './Routes/Register'
import AdminCaracteristicas from './Routes/AdminCaracteristicas'
import Login from './Routes/Login'
import AdminFilter from './Routes/AdminFilter'
import Perfil from './Routes/Perfil'
import AdminPrivilegios from './Routes/AdminPrivilegios'


function App() {


  const [products, setProducts] = useState(
[


  { id:1,name:'Spiderman infantil',price:21.99,mainCategory:'Niños',subCategory:'Comic',imageUrl:'https://m.media-amazon.com/images/I/71RwXhXL71L._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Traje ajustado de licra con estampado de telaraña, máscara y lanzadores de telarañas',largeDescription:'Traje ajustado de licra con estampado de telaraña, máscara y lanzadores de telarañas'},
  { id:2,name:'Bombero infantil',price:19.75,mainCategory:'Niños',subCategory:'Oficios',imageUrl:'https://m.media-amazon.com/images/I/81F8WH2Oy-L._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Mono de trabajo resistente al fuego, casco y herramientas',largeDescription:'Mono de trabajo resistente al fuego, casco y herramientas'},
  { id:3,name:'Cleopatra adulto',price:25.49,mainCategory:'Mujer',subCategory:'Personaje histórico',imageUrl:'https://m.media-amazon.com/images/I/61ej8HfX28L._AC_SY550_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Vestido largo de tela brillante, collar y brazaletes dorados',largeDescription:'Vestido largo de tela brillante, collar y brazaletes dorados'},
  { id:4,name:'Arlequin adulto',price:32.47,mainCategory:'Mujer',subCategory:'Comic',imageUrl:'https://m.media-amazon.com/images/I/61rkb1JXfoL._AC_SL1470_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono de cuerpo entero negro y rojo decorado con rombos, volante rojo en el huello y antifaz negro.',largeDescription:'Mono de cuerpo entero negro y rojo decorado con rombos, volante rojo en el huello y antifaz negro.'},
  { id:5,name:'Caballero medieval adulto',price:39.98,mainCategory:'Hombre',subCategory:'Personaje histórico',imageUrl:'https://m.media-amazon.com/images/I/91huuXnwjyL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Túnica con capa, cinturón, 2 medallones y puños. Otros accesorios no están incluidos.',largeDescription:'Túnica con capa, cinturón, 2 medallones y puños. Otros accesorios no están incluidos.'},
  { id:6,name:'Maléfica adulto',price:64.53,mainCategory:'Mujer',subCategory:'Cuento de hadas',imageUrl:'https://m.media-amazon.com/images/I/81aNvdNWr0L._AC_SY879_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Vestido con broche desmontable y tocado de personaje',largeDescription:'Vestido con broche desmontable y tocado de personaje'},
  { id:7,name:'Elvis adulto',price:84.36,mainCategory:'Hombre',subCategory:'Personaje histórico',imageUrl:'https://m.media-amazon.com/images/I/71s9MApCJNL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono blanco con gliter dorado, estrellas y pedrería impresa',largeDescription:'Mono blanco con gliter dorado, estrellas y pedrería impresa'},
  { id:8,name:'Dinosaurio infantil',price:34.40,mainCategory:'Niños',subCategory:'Animal',imageUrl:'https://m.media-amazon.com/images/I/51wckD-VogL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Mono cómodo para niños pequeños, adaptable con la edad, de franela de alta calidad.',largeDescription:'Mono cómodo para niños pequeños, adaptable con la edad, de franela de alta calidad.'},
  { id:9,name:'Chuky mascota',price:17.69,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61j5cIUdZxL.__AC_SY300_SX300_QL70_ML2_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Hecho de algodón transpirable, suave y amigable para la piel y fibra de poliéster, para la mascota.',largeDescription:'Hecho de algodón transpirable, suave y amigable para la piel y fibra de poliéster, para la mascota.'},
  { id:10,name:'Murciélago mascota',price:21.36,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61-nzdIJKRL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Alas de muerciélago para mascota, con correa y cascabel de calabaza',largeDescription:'Alas de muerciélago para mascota, con correa y cascabel de calabaza'},
  { id:11,name:'Princesa Ogro adulto',price:22.00,mainCategory:'Mujer',subCategory:'Cuento de hadas',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787266/disfraz-de-princesa-ogro.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Vestido verde de estilo medieval para mujer.Incluye vestido y diadema con Orejas.Corona NO incluida.',largeDescription:'Vestido verde de estilo medieval para mujer.Incluye vestido y diadema con Orejas.Corona NO incluida.'},
  { id:12,name:'Galo Obelix deluxe adulto',price:25.75,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787265/disfraz-de-obelix-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Pantalon rayado con cinturon verde y camiseta simil piel. Casco incluido',largeDescription:'Pantalon rayado con cinturon verde y camiseta simil piel. Casco incluido'},
  { id:13,name:'Mago gris deluxe adulto',price:26.00,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787263/disfraz-de-mago-gris.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye tunica, sombrero y cinturon.',largeDescription:'Incluye tunica, sombrero y cinturon.'},
  { id:14,name:'Cavernicola Betty adulto',price:25.50,mainCategory:'Mujer',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787262/disfraz-de-betty-cavernicola.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Betty Picapiedra para mujer en talla M.Incluye vestido y gorro(peluca).',largeDescription:'Betty Picapiedra para mujer en talla M.Incluye vestido y gorro(peluca).'},
  { id:15,name:'Harry Potter infantil',price:22.30,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787267/disfraz-harry-potter-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Tunica de licencia oficial de Grifindor como la de Harry Potter, El disfraz incluye la tunica de color negro con forro granate en la parte interior de la capucha.',largeDescription:'Tunica de licencia oficial de Grifindor como la de Harry Potter, El disfraz incluye la tunica de color negro con forro granate en la parte interior de la capucha.'},
  { id:16,name:'Marge Simpson adulto',price:21.75,mainCategory:'Mujer',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787263/disfraz-de-madre-de-dibujos-amarillos.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Vestido en verde amarillo con collar y peluca',largeDescription:'Vestido en verde amarillo con collar y peluca'},
  { id:17,name:'Fontanero Mario Bros adulto',price:20.80,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787264/disfraz-de-mario_bros.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Jardinero en azul y camiseta roja. Incluye buzo y gorra.',largeDescription:'Jardinero en azul y camiseta roja. Incluye buzo y gorra.'},
  { id:18,name:'Mario Bros infantil',price:19.65,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787264/disfraz-de-mario-bros-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Incluye peto con camiseta, gorra y bigote.',largeDescription:'Incluye peto con camiseta, gorra y bigote.'},
  { id:19,name:'Buzz Lightyear Infantil',price:22.00,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787262/disfraz-de-buzz-lightyear-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye buzo y capucha de tela.',largeDescription:'Incluye buzo y capucha de tela.'},
  { id:20,name:'Avatar deluxe adulto',price:32.00,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787262/disfraz-de-avatar.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Incluye mono, cinturon, delantal y muñequeras.',largeDescription:'Incluye mono, cinturon, delantal y muñequeras.'},
  { id:21,name:'Pikachu infantil',price:21.99,mainCategory:'Niños',subCategory:'Anime',imageUrl:'https://m.media-amazon.com/images/I/817Af8-nswL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Mono de una pieza',largeDescription:'Mono de una pieza'},
  { id:22,name:'SpiderDog mascota',price:8.22,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/71Xb+xZPlhL._AC_SY500_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Chaquetilla con accesorios aracnidos',largeDescription:'Chaquetilla con accesorios aracnidos'},
  { id:23,name:'Fantasma Scream adulto',price:24.49,mainCategory:'Hombre',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61UzIjubFrL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Mascara y Traje, dos piezas',largeDescription:'Mascara y Traje, dos piezas'},
  { id:24,name:'BabyShark adulto',price:32.47,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://m.media-amazon.com/images/I/61qmbh1-bIL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Mono Traje de 1 cierre de cremallera',largeDescription:'Mono Traje de 1 cierre de cremallera'},
  { id:25,name:'T-Rex Divertido adulto',price:39.89,mainCategory:'Hombre',subCategory:'Animal',imageUrl:'https://m.media-amazon.com/images/I/91w-z3hEn9L._AC_SX522_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono Traje de 1 cierre de cremallera',largeDescription:'Mono Traje de 1 cierre de cremallera'},
  { id:26,name:'Monja Picara adulto',price:21.99,mainCategory:'Mujer',subCategory:'Religioso',imageUrl:'https://m.media-amazon.com/images/I/81E60yM4CoL._AC_SY550_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'El disfraz unisex incluye bata negra con cuello y puños blancos adjuntos, cinturón de cuerda blanca y tocado en blanco y negro.',largeDescription:'El disfraz unisex incluye bata negra con cuello y puños blancos adjuntos, cinturón de cuerda blanca y tocado en blanco y negro.'},
  { id:27,name:'Morphsuits adulto',price:19.75,mainCategory:'Hombre',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61g7JfSdWDL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Disfraz oficial de Morphsuit: Morphsuits, tampoco sabemos lo que es, pero es espeluznante. Eso es todo lo que necesitas saber',largeDescription:'Disfraz oficial de Morphsuit: Morphsuits, tampoco sabemos lo que es, pero es espeluznante. Eso es todo lo que necesitas saber'},
  { id:28,name:'mickey mouse infantil',price:20.50,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://m.media-amazon.com/images/I/61dGYmSJfHL._AC_SY879_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'El producto incluye: Mono con chaqueta adjunta, pajarita adjunta y capucha de personaje.',largeDescription:'El producto incluye: Mono con chaqueta adjunta, pajarita adjunta y capucha de personaje.'},
  { id:29,name:'Kimono Inuyasha infantil',price:38.50,mainCategory:'Niños',subCategory:'Anime',imageUrl:'https://http2.mlstatic.com/D_NQ_NP_971387-MLC74535238874_022024-O.webp',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Disfraces Traje Kimono De Cosplay De Inuyasha Para Hombre Y Mujer Anime Kimono Japonés Ropa De Rendimiento Del Drama De Halloween Fiesta De Carnaval',largeDescription:'Disfraces Traje Kimono De Cosplay De Inuyasha Para Hombre Y Mujer Anime Kimono Japonés Ropa De Rendimiento Del Drama De Halloween Fiesta De Carnaval'},
  { id:30,name:'Reina Medieval adulto',price:28.20,mainCategory:'Mujer',subCategory:'Personaje histórico',imageUrl:'https://http2.mlstatic.com/D_NQ_NP_2X_906812-MLC70747711699_072023-F.webp',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'El disfraz está compuesto por un vestido largo de color azul y negro, corona plateada, y un cinturón. Además cuenta con ribete plateado metálico, estampado de red y damasco, escote de hombro descubierto, mangas acampanadas y falda de terciopelo.',largeDescription:'El disfraz está compuesto por un vestido largo de color azul y negro, corona plateada, y un cinturón. Además cuenta con ribete plateado metálico, estampado de red y damasco, escote de hombro descubierto, mangas acampanadas y falda de terciopelo.'},
  { id:31,name:'Gatubela adulto',price:20.50,mainCategory:'Mujer',subCategory:'Comic',imageUrl:'https://http2.mlstatic.com/D_NQ_NP_2X_779979-MLC74367778058_022024-F.webp',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono Ajustado cuero imitación',largeDescription:'Mono Ajustado cuero imitación'},
  { id:32,name:'Chitara adulto',price:40.00,mainCategory:'Mujer',subCategory:'Comic',imageUrl:'https://m.media-amazon.com/images/I/71Ih0+KGaXL._AC_SX466_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono Ajustado piel imitación',largeDescription:'Mono Ajustado piel imitación'},
  { id:33,name:'Spiderman deluxe adulto',price:45.00,mainCategory:'Hombre',subCategory:'Comic',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717902811/disfraz-de-spiderman-deluxe-para-adulto_mhvu1o.jpg',imageURL_2:'https://res.cloudinary.com/daawucxot/image/upload/v1717902811/disfraz-de-spiderman-deluxe-para-adulto_mhvu1o.jpg',imageURL_3:'',imageURL_4:'',size:'XL',description:'Incluye mono y máscara',largeDescription:'Incluye mono y máscara'},
  { id:34,name:'Spiderman deluxe infantil',price:31.99,mainCategory:'Niños',subCategory:'Comic',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717902871/disfraz-de-spiderman-deluxe-para-nino_ccgxue.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye mono musculoso con cubre botas y máscara',largeDescription:'Incluye mono musculoso con cubre botas y máscara'},
  { id:35,name:'Spiderman mascota',price:26.50,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717902885/disfraz-de-spiderman-para-perro_zoo2hm.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye camiseta y gorro',largeDescription:'Incluye camiseta y gorro'},
  { id:36,name:'Spiderman negro y rojo infantil',price:21.99,mainCategory:'Niños',subCategory:'Comic',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717909409/disfraz-de-spiderman-negro-y-rojo-para-nino-spider-man-3-_kwc997.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye mono musculoso con cubre botas y máscara',largeDescription:'Incluye mono musculoso con cubre botas y máscara'},
  { id:37,name:'Spiderman infantil',price:21.99,mainCategory:'Niños',subCategory:'Comic',imageUrl:'https://m.media-amazon.com/images/I/71RwXhXL71L._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Traje ajustado de licra con estampado de telaraña, máscara y lanzadores de telarañas',largeDescription:'Traje ajustado de licra con estampado de telaraña, máscara y lanzadores de telarañas'},
  { id:38,name:'Bombero infantil',price:19.75,mainCategory:'Niños',subCategory:'Oficios',imageUrl:'https://m.media-amazon.com/images/I/81F8WH2Oy-L._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Mono de trabajo resistente al fuego, casco y herramientas',largeDescription:'Mono de trabajo resistente al fuego, casco y herramientas'},
  { id:39,name:'Cleopatra adulto',price:25.49,mainCategory:'Mujer',subCategory:'Personaje histórico',imageUrl:'https://m.media-amazon.com/images/I/61ej8HfX28L._AC_SY550_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Vestido largo de tela brillante, collar y brazaletes dorados',largeDescription:'Vestido largo de tela brillante, collar y brazaletes dorados'},
  { id:40,name:'Arlequin adulto',price:32.47,mainCategory:'Mujer',subCategory:'Comic',imageUrl:'https://m.media-amazon.com/images/I/61rkb1JXfoL._AC_SL1470_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono de cuerpo entero negro y rojo decorado con rombos, volante rojo en el huello y antifaz negro.',largeDescription:'Mono de cuerpo entero negro y rojo decorado con rombos, volante rojo en el huello y antifaz negro.'},
  { id:41,name:'Caballero medieval adulto',price:39.98,mainCategory:'Hombre',subCategory:'Personaje histórico',imageUrl:'https://m.media-amazon.com/images/I/91huuXnwjyL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Túnica con capa, cinturón, 2 medallones y puños. Otros accesorios no están incluidos.',largeDescription:'Túnica con capa, cinturón, 2 medallones y puños. Otros accesorios no están incluidos.'},
  { id:42,name:'Maléfica adulto',price:64.53,mainCategory:'Mujer',subCategory:'Cuento de hadas',imageUrl:'https://m.media-amazon.com/images/I/81aNvdNWr0L._AC_SY879_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Vestido con broche desmontable y tocado de personaje',largeDescription:'Vestido con broche desmontable y tocado de personaje'},
  { id:43,name:'Elvis adulto',price:84.36,mainCategory:'Hombre',subCategory:'Personaje histórico',imageUrl:'https://m.media-amazon.com/images/I/71s9MApCJNL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono blanco con gliter dorado, estrellas y pedrería impresa',largeDescription:'Mono blanco con gliter dorado, estrellas y pedrería impresa'},
  { id:44,name:'Dinosaurio infantil',price:34.40,mainCategory:'Niños',subCategory:'Animal',imageUrl:'https://m.media-amazon.com/images/I/51wckD-VogL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Mono cómodo para niños pequeños, adaptable con la edad, de franela de alta calidad.',largeDescription:'Mono cómodo para niños pequeños, adaptable con la edad, de franela de alta calidad.'},
  { id:45,name:'Chuky mascota',price:17.69,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61j5cIUdZxL.__AC_SY300_SX300_QL70_ML2_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Hecho de algodón transpirable, suave y amigable para la piel y fibra de poliéster, para la mascota.',largeDescription:'Hecho de algodón transpirable, suave y amigable para la piel y fibra de poliéster, para la mascota.'},
  { id:46,name:'Murciélago mascota',price:21.36,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61-nzdIJKRL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Alas de muerciélago para mascota, con correa y cascabel de calabaza',largeDescription:'Alas de muerciélago para mascota, con correa y cascabel de calabaza'},
  { id:47,name:'Princesa Ogro adulto',price:22.00,mainCategory:'Mujer',subCategory:'Cuento de hadas',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787266/disfraz-de-princesa-ogro.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Vestido verde de estilo medieval para mujer.Incluye vestido y diadema con Orejas.Corona NO incluida.',largeDescription:'Vestido verde de estilo medieval para mujer.Incluye vestido y diadema con Orejas.Corona NO incluida.'},
  { id:48,name:'Galo Obelix deluxe adulto',price:25.75,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787265/disfraz-de-obelix-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Pantalon rayado con cinturon verde y camiseta simil piel. Casco incluido',largeDescription:'Pantalon rayado con cinturon verde y camiseta simil piel. Casco incluido'},
  { id:49,name:'Mago gris deluxe adulto',price:26.00,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787263/disfraz-de-mago-gris.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye tunica, sombrero y cinturon.',largeDescription:'Incluye tunica, sombrero y cinturon.'},
  { id:50,name:'Cavernicola Betty adulto',price:25.50,mainCategory:'Mujer',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787262/disfraz-de-betty-cavernicola.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Betty Picapiedra para mujer en talla M.Incluye vestido y gorro(peluca).',largeDescription:'Betty Picapiedra para mujer en talla M.Incluye vestido y gorro(peluca).'},
  { id:51,name:'Harry Potter infantil',price:22.30,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787267/disfraz-harry-potter-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Tunica de licencia oficial de Grifindor como la de Harry Potter, El disfraz incluye la tunica de color negro con forro granate en la parte interior de la capucha.',largeDescription:'Tunica de licencia oficial de Grifindor como la de Harry Potter, El disfraz incluye la tunica de color negro con forro granate en la parte interior de la capucha.'},
  { id:52,name:'Marge Simpson adulto',price:21.75,mainCategory:'Mujer',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787263/disfraz-de-madre-de-dibujos-amarillos.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Vestido en verde amarillo con collar y peluca',largeDescription:'Vestido en verde amarillo con collar y peluca'},
  { id:53,name:'Fontanero Mario Bros adulto',price:20.80,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787264/disfraz-de-mario_bros.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Jardinero en azul y camiseta roja. Incluye buzo y gorra.',largeDescription:'Jardinero en azul y camiseta roja. Incluye buzo y gorra.'},
  { id:54,name:'Mario Bros infantil',price:19.65,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787264/disfraz-de-mario-bros-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Incluye peto con camiseta, gorra y bigote.',largeDescription:'Incluye peto con camiseta, gorra y bigote.'},
  { id:55,name:'Buzz Lightyear Infantil',price:22.00,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787262/disfraz-de-buzz-lightyear-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye buzo y capucha de tela.',largeDescription:'Incluye buzo y capucha de tela.'},
  { id:56,name:'Avatar deluxe adulto',price:32.00,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787262/disfraz-de-avatar.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Incluye mono, cinturon, delantal y muñequeras.',largeDescription:'Incluye mono, cinturon, delantal y muñequeras.'},
  { id:57,name:'Pikachu infantil',price:21.99,mainCategory:'Niños',subCategory:'Anime',imageUrl:'https://m.media-amazon.com/images/I/817Af8-nswL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Mono de una pieza',largeDescription:'Mono de una pieza'},
  { id:58,name:'SpiderDog mascota',price:8.22,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/71Xb+xZPlhL._AC_SY500_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Chaquetilla con accesorios aracnidos',largeDescription:'Chaquetilla con accesorios aracnidos'},
  { id:59,name:'Fantasma Scream adulto',price:24.49,mainCategory:'Hombre',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61UzIjubFrL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Mascara y Traje, dos piezas',largeDescription:'Mascara y Traje, dos piezas'},
  { id:60,name:'BabyShark adulto',price:32.47,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://m.media-amazon.com/images/I/61qmbh1-bIL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Mono Traje de 1 cierre de cremallera',largeDescription:'Mono Traje de 1 cierre de cremallera'},
  { id:61,name:'T-Rex Divertido adulto',price:39.89,mainCategory:'Hombre',subCategory:'Animal',imageUrl:'https://m.media-amazon.com/images/I/91w-z3hEn9L._AC_SX522_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono Traje de 1 cierre de cremallera',largeDescription:'Mono Traje de 1 cierre de cremallera'},
  { id:62,name:'Monja Picara adulto',price:21.99,mainCategory:'Mujer',subCategory:'Religioso',imageUrl:'https://m.media-amazon.com/images/I/81E60yM4CoL._AC_SY550_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'El disfraz unisex incluye bata negra con cuello y puños blancos adjuntos, cinturón de cuerda blanca y tocado en blanco y negro.',largeDescription:'El disfraz unisex incluye bata negra con cuello y puños blancos adjuntos, cinturón de cuerda blanca y tocado en blanco y negro.'},
  { id:63,name:'Morphsuits adulto',price:19.75,mainCategory:'Hombre',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61g7JfSdWDL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Disfraz oficial de Morphsuit: Morphsuits, tampoco sabemos lo que es, pero es espeluznante. Eso es todo lo que necesitas saber',largeDescription:'Disfraz oficial de Morphsuit: Morphsuits, tampoco sabemos lo que es, pero es espeluznante. Eso es todo lo que necesitas saber'},
  { id:64,name:'mickey mouse infantil',price:20.50,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://m.media-amazon.com/images/I/61dGYmSJfHL._AC_SY879_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'El producto incluye: Mono con chaqueta adjunta, pajarita adjunta y capucha de personaje.',largeDescription:'El producto incluye: Mono con chaqueta adjunta, pajarita adjunta y capucha de personaje.'},
  { id:65,name:'Kimono Inuyasha infantil',price:38.50,mainCategory:'Niños',subCategory:'Anime',imageUrl:'https://http2.mlstatic.com/D_NQ_NP_971387-MLC74535238874_022024-O.webp',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Disfraces Traje Kimono De Cosplay De Inuyasha Para Hombre Y Mujer Anime Kimono Japonés Ropa De Rendimiento Del Drama De Halloween Fiesta De Carnaval',largeDescription:'Disfraces Traje Kimono De Cosplay De Inuyasha Para Hombre Y Mujer Anime Kimono Japonés Ropa De Rendimiento Del Drama De Halloween Fiesta De Carnaval'},
  { id:66,name:'Reina Medieval adulto',price:28.20,mainCategory:'Mujer',subCategory:'Personaje histórico',imageUrl:'https://http2.mlstatic.com/D_NQ_NP_2X_906812-MLC70747711699_072023-F.webp',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'El disfraz está compuesto por un vestido largo de color azul y negro, corona plateada, y un cinturón. Además cuenta con ribete plateado metálico, estampado de red y damasco, escote de hombro descubierto, mangas acampanadas y falda de terciopelo.',largeDescription:'El disfraz está compuesto por un vestido largo de color azul y negro, corona plateada, y un cinturón. Además cuenta con ribete plateado metálico, estampado de red y damasco, escote de hombro descubierto, mangas acampanadas y falda de terciopelo.'},
  { id:67,name:'Gatubela adulto',price:20.50,mainCategory:'Mujer',subCategory:'Comic',imageUrl:'https://http2.mlstatic.com/D_NQ_NP_2X_779979-MLC74367778058_022024-F.webp',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono Ajustado cuero imitación',largeDescription:'Mono Ajustado cuero imitación'},
  { id:68,name:'Chitara adulto',price:40.00,mainCategory:'Mujer',subCategory:'Comic',imageUrl:'https://m.media-amazon.com/images/I/71Ih0+KGaXL._AC_SX466_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono Ajustado piel imitación',largeDescription:'Mono Ajustado piel imitación'},
  { id:69,name:'Spiderman deluxe adulto',price:45.00,mainCategory:'Hombre',subCategory:'Comic',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717902811/disfraz-de-spiderman-deluxe-para-adulto_mhvu1o.jpg',imageURL_2:'https://res.cloudinary.com/daawucxot/image/upload/v1717902811/disfraz-de-spiderman-deluxe-para-adulto_mhvu1o.jpg',imageURL_3:'',imageURL_4:'',size:'XL',description:'Incluye mono y máscara',largeDescription:'Incluye mono y máscara'},
  { id:70,name:'Spiderman deluxe infantil',price:31.99,mainCategory:'Niños',subCategory:'Comic',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717902871/disfraz-de-spiderman-deluxe-para-nino_ccgxue.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye mono musculoso con cubre botas y máscara',largeDescription:'Incluye mono musculoso con cubre botas y máscara'},
  { id:71,name:'Spiderman mascota',price:26.50,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717902885/disfraz-de-spiderman-para-perro_zoo2hm.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye camiseta y gorro',largeDescription:'Incluye camiseta y gorro'},
  { id:72,name:'Spiderman negro y rojo infantil',price:21.99,mainCategory:'Niños',subCategory:'Comic',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717909409/disfraz-de-spiderman-negro-y-rojo-para-nino-spider-man-3-_kwc997.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye mono musculoso con cubre botas y máscara',largeDescription:'Incluye mono musculoso con cubre botas y máscara'},
  { id:73,name:'Spiderman infantil',price:21.99,mainCategory:'Niños',subCategory:'Comic',imageUrl:'https://m.media-amazon.com/images/I/71RwXhXL71L._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Traje ajustado de licra con estampado de telaraña, máscara y lanzadores de telarañas',largeDescription:'Traje ajustado de licra con estampado de telaraña, máscara y lanzadores de telarañas'},
  { id:74,name:'Bombero infantil',price:19.75,mainCategory:'Niños',subCategory:'Oficios',imageUrl:'https://m.media-amazon.com/images/I/81F8WH2Oy-L._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Mono de trabajo resistente al fuego, casco y herramientas',largeDescription:'Mono de trabajo resistente al fuego, casco y herramientas'},
  { id:75,name:'Cleopatra adulto',price:25.49,mainCategory:'Mujer',subCategory:'Personaje histórico',imageUrl:'https://m.media-amazon.com/images/I/61ej8HfX28L._AC_SY550_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Vestido largo de tela brillante, collar y brazaletes dorados',largeDescription:'Vestido largo de tela brillante, collar y brazaletes dorados'},
  { id:76,name:'Arlequin adulto',price:32.47,mainCategory:'Mujer',subCategory:'Comic',imageUrl:'https://m.media-amazon.com/images/I/61rkb1JXfoL._AC_SL1470_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono de cuerpo entero negro y rojo decorado con rombos, volante rojo en el huello y antifaz negro.',largeDescription:'Mono de cuerpo entero negro y rojo decorado con rombos, volante rojo en el huello y antifaz negro.'},
  { id:77,name:'Caballero medieval adulto',price:39.98,mainCategory:'Hombre',subCategory:'Personaje histórico',imageUrl:'https://m.media-amazon.com/images/I/91huuXnwjyL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Túnica con capa, cinturón, 2 medallones y puños. Otros accesorios no están incluidos.',largeDescription:'Túnica con capa, cinturón, 2 medallones y puños. Otros accesorios no están incluidos.'},
  { id:78,name:'Maléfica adulto',price:64.53,mainCategory:'Mujer',subCategory:'Cuento de hadas',imageUrl:'https://m.media-amazon.com/images/I/81aNvdNWr0L._AC_SY879_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Vestido con broche desmontable y tocado de personaje',largeDescription:'Vestido con broche desmontable y tocado de personaje'},
  { id:79,name:'Elvis adulto',price:84.36,mainCategory:'Hombre',subCategory:'Personaje histórico',imageUrl:'https://m.media-amazon.com/images/I/71s9MApCJNL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono blanco con gliter dorado, estrellas y pedrería impresa',largeDescription:'Mono blanco con gliter dorado, estrellas y pedrería impresa'},
  { id:80,name:'Dinosaurio infantil',price:34.40,mainCategory:'Niños',subCategory:'Animal',imageUrl:'https://m.media-amazon.com/images/I/51wckD-VogL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Mono cómodo para niños pequeños, adaptable con la edad, de franela de alta calidad.',largeDescription:'Mono cómodo para niños pequeños, adaptable con la edad, de franela de alta calidad.'},
  { id:81,name:'Chuky mascota',price:17.69,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61j5cIUdZxL.__AC_SY300_SX300_QL70_ML2_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Hecho de algodón transpirable, suave y amigable para la piel y fibra de poliéster, para la mascota.',largeDescription:'Hecho de algodón transpirable, suave y amigable para la piel y fibra de poliéster, para la mascota.'},
  { id:82,name:'Murciélago mascota',price:21.36,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61-nzdIJKRL._AC_SX679_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Alas de muerciélago para mascota, con correa y cascabel de calabaza',largeDescription:'Alas de muerciélago para mascota, con correa y cascabel de calabaza'},
  { id:83,name:'Princesa Ogro adulto',price:22.00,mainCategory:'Mujer',subCategory:'Cuento de hadas',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787266/disfraz-de-princesa-ogro.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Vestido verde de estilo medieval para mujer.Incluye vestido y diadema con Orejas.Corona NO incluida.',largeDescription:'Vestido verde de estilo medieval para mujer.Incluye vestido y diadema con Orejas.Corona NO incluida.'},
  { id:84,name:'Galo Obelix deluxe adulto',price:25.75,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787265/disfraz-de-obelix-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Pantalon rayado con cinturon verde y camiseta simil piel. Casco incluido',largeDescription:'Pantalon rayado con cinturon verde y camiseta simil piel. Casco incluido'},
  { id:85,name:'Mago gris deluxe adulto',price:26.00,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787263/disfraz-de-mago-gris.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye tunica, sombrero y cinturon.',largeDescription:'Incluye tunica, sombrero y cinturon.'},
  { id:86,name:'Cavernicola Betty adulto',price:25.50,mainCategory:'Mujer',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787262/disfraz-de-betty-cavernicola.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Betty Picapiedra para mujer en talla M.Incluye vestido y gorro(peluca).',largeDescription:'Betty Picapiedra para mujer en talla M.Incluye vestido y gorro(peluca).'},
  { id:87,name:'Harry Potter infantil',price:22.30,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787267/disfraz-harry-potter-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Tunica de licencia oficial de Grifindor como la de Harry Potter, El disfraz incluye la tunica de color negro con forro granate en la parte interior de la capucha.',largeDescription:'Tunica de licencia oficial de Grifindor como la de Harry Potter, El disfraz incluye la tunica de color negro con forro granate en la parte interior de la capucha.'},
  { id:88,name:'Marge Simpson adulto',price:21.75,mainCategory:'Mujer',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787263/disfraz-de-madre-de-dibujos-amarillos.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Vestido en verde amarillo con collar y peluca',largeDescription:'Vestido en verde amarillo con collar y peluca'},
  { id:89,name:'Fontanero Mario Bros adulto',price:20.80,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787264/disfraz-de-mario_bros.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Jardinero en azul y camiseta roja. Incluye buzo y gorra.',largeDescription:'Jardinero en azul y camiseta roja. Incluye buzo y gorra.'},
  { id:90,name:'Mario Bros infantil',price:19.65,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787264/disfraz-de-mario-bros-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Incluye peto con camiseta, gorra y bigote.',largeDescription:'Incluye peto con camiseta, gorra y bigote.'},
  { id:91,name:'Buzz Lightyear Infantil',price:22.00,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787262/disfraz-de-buzz-lightyear-infantil.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye buzo y capucha de tela.',largeDescription:'Incluye buzo y capucha de tela.'},
  { id:92,name:'Avatar deluxe adulto',price:32.00,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1715787262/disfraz-de-avatar.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'Incluye mono, cinturon, delantal y muñequeras.',largeDescription:'Incluye mono, cinturon, delantal y muñequeras.'},
  { id:93,name:'Pikachu infantil',price:21.99,mainCategory:'Niños',subCategory:'Anime',imageUrl:'https://m.media-amazon.com/images/I/817Af8-nswL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Mono de una pieza',largeDescription:'Mono de una pieza'},
  { id:94,name:'SpiderDog mascota',price:8.22,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/71Xb+xZPlhL._AC_SY500_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Chaquetilla con accesorios aracnidos',largeDescription:'Chaquetilla con accesorios aracnidos'},
  { id:95,name:'Fantasma Scream adulto',price:24.49,mainCategory:'Hombre',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61UzIjubFrL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'XL',description:'Mascara y Traje, dos piezas',largeDescription:'Mascara y Traje, dos piezas'},
  { id:96,name:'BabyShark adulto',price:32.47,mainCategory:'Hombre',subCategory:'Personaje ficción',imageUrl:'https://m.media-amazon.com/images/I/61qmbh1-bIL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Mono Traje de 1 cierre de cremallera',largeDescription:'Mono Traje de 1 cierre de cremallera'},
  { id:97,name:'T-Rex Divertido adulto',price:39.89,mainCategory:'Hombre',subCategory:'Animal',imageUrl:'https://m.media-amazon.com/images/I/91w-z3hEn9L._AC_SX522_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono Traje de 1 cierre de cremallera',largeDescription:'Mono Traje de 1 cierre de cremallera'},
  { id:98,name:'Monja Picara adulto',price:21.99,mainCategory:'Mujer',subCategory:'Religioso',imageUrl:'https://m.media-amazon.com/images/I/81E60yM4CoL._AC_SY550_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'El disfraz unisex incluye bata negra con cuello y puños blancos adjuntos, cinturón de cuerda blanca y tocado en blanco y negro.',largeDescription:'El disfraz unisex incluye bata negra con cuello y puños blancos adjuntos, cinturón de cuerda blanca y tocado en blanco y negro.'},
  { id:99,name:'Morphsuits adulto',price:19.75,mainCategory:'Hombre',subCategory:'Hallowen',imageUrl:'https://m.media-amazon.com/images/I/61g7JfSdWDL._AC_SX569_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Disfraz oficial de Morphsuit: Morphsuits, tampoco sabemos lo que es, pero es espeluznante. Eso es todo lo que necesitas saber',largeDescription:'Disfraz oficial de Morphsuit: Morphsuits, tampoco sabemos lo que es, pero es espeluznante. Eso es todo lo que necesitas saber'},
  { id:100,name:'mickey mouse infantil',price:20.50,mainCategory:'Niños',subCategory:'Personaje ficción',imageUrl:'https://m.media-amazon.com/images/I/61dGYmSJfHL._AC_SY879_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'El producto incluye: Mono con chaqueta adjunta, pajarita adjunta y capucha de personaje.',largeDescription:'El producto incluye: Mono con chaqueta adjunta, pajarita adjunta y capucha de personaje.'},
  { id:101,name:'Kimono Inuyasha infantil',price:38.50,mainCategory:'Niños',subCategory:'Anime',imageUrl:'https://http2.mlstatic.com/D_NQ_NP_971387-MLC74535238874_022024-O.webp',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'M',description:'Disfraces Traje Kimono De Cosplay De Inuyasha Para Hombre Y Mujer Anime Kimono Japonés Ropa De Rendimiento Del Drama De Halloween Fiesta De Carnaval',largeDescription:'Disfraces Traje Kimono De Cosplay De Inuyasha Para Hombre Y Mujer Anime Kimono Japonés Ropa De Rendimiento Del Drama De Halloween Fiesta De Carnaval'},
  { id:102,name:'Reina Medieval adulto',price:28.20,mainCategory:'Mujer',subCategory:'Personaje histórico',imageUrl:'https://http2.mlstatic.com/D_NQ_NP_2X_906812-MLC70747711699_072023-F.webp',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'L',description:'El disfraz está compuesto por un vestido largo de color azul y negro, corona plateada, y un cinturón. Además cuenta con ribete plateado metálico, estampado de red y damasco, escote de hombro descubierto, mangas acampanadas y falda de terciopelo.',largeDescription:'El disfraz está compuesto por un vestido largo de color azul y negro, corona plateada, y un cinturón. Además cuenta con ribete plateado metálico, estampado de red y damasco, escote de hombro descubierto, mangas acampanadas y falda de terciopelo.'},
  { id:103,name:'Gatubela adulto',price:20.50,mainCategory:'Mujer',subCategory:'Comic',imageUrl:'https://http2.mlstatic.com/D_NQ_NP_2X_779979-MLC74367778058_022024-F.webp',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono Ajustado cuero imitación',largeDescription:'Mono Ajustado cuero imitación'},
  { id:104,name:'Chitara adulto',price:40.00,mainCategory:'Mujer',subCategory:'Comic',imageUrl:'https://m.media-amazon.com/images/I/71Ih0+KGaXL._AC_SX466_.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Mono Ajustado piel imitación',largeDescription:'Mono Ajustado piel imitación'},
  { id:105,name:'Spiderman deluxe adulto',price:45.00,mainCategory:'Hombre',subCategory:'Comic',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717902811/disfraz-de-spiderman-deluxe-para-adulto_mhvu1o.jpg',imageURL_2:'https://res.cloudinary.com/daawucxot/image/upload/v1717902811/disfraz-de-spiderman-deluxe-para-adulto_mhvu1o.jpg',imageURL_3:'',imageURL_4:'',size:'XL',description:'Incluye mono y máscara',largeDescription:'Incluye mono y máscara'},
  { id:106,name:'Spiderman deluxe infantil',price:31.99,mainCategory:'Niños',subCategory:'Comic',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717902871/disfraz-de-spiderman-deluxe-para-nino_ccgxue.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye mono musculoso con cubre botas y máscara',largeDescription:'Incluye mono musculoso con cubre botas y máscara'},
  { id:107,name:'Spiderman mascota',price:26.50,mainCategory:'Mascotas',subCategory:'Hallowen',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717902885/disfraz-de-spiderman-para-perro_zoo2hm.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye camiseta y gorro',largeDescription:'Incluye camiseta y gorro'},
  { id:108,name:'Spiderman negro y rojo infantil',price:21.99,mainCategory:'Niños',subCategory:'Comic',imageUrl:'https://res.cloudinary.com/daawucxot/image/upload/v1717909409/disfraz-de-spiderman-negro-y-rojo-para-nino-spider-man-3-_kwc997.jpg',imageURL_2:'',imageURL_3:'',imageURL_4:'',size:'S',description:'Incluye mono musculoso con cubre botas y máscara',largeDescription:'Incluye mono musculoso con cubre botas y máscara'},

]);





//console.log(products);
const handleAddProduct = (newProduct) => {
console.log('Nuevo producto:', newProduct);
setProducts([...products, newProduct]);
};

return (
  <div>
    <Header />
    <Routes>
      <Route path="/" element={<Home products={products} onAddProduct={handleAddProduct}/>} />
      <Route path="/admin" element={<Admin />} />
      <Route path="/card/:id" element={<Detail products={products} />} />
      <Route
        path="/admin/AddProduct"
        element={<AddProduct products={products} setProducts={setProducts} onAddProduct={handleAddProduct} />}
      />
      <Route path="/Register" element={<Register/>} />
      <Route path="/Login" element={<Login/>} />
      <Route path="/Admin/AdminCaracteristicas" element={<AdminCaracteristicas/>} />
      
      <Route path="/adminFilter" element={<AdminFilter/>} />
      <Route path="/AdminPrivilegios" element={<AdminPrivilegios/>} />

      <Route path='/Perfil' element={<Perfil/>} />
      </Routes>
    <Footer />
  </div>
);
}


export default App
